version: '3.8'
services:
  app:
    build: .
    container_name: app-recipes
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/animal_shop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    networks:
      - shared-network
    ports:
      - "8095:8095"
networks:
  shared-network:
    external: true
